apiVersion: apps/v1
kind: Deployment
metadata:
  name: tinyproxy
  annotations:
    harness.io/skip-file-for-deploy: true 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tinyproxy
  template:
    metadata:
      labels:
        app: tinyproxy
    spec:
      containers:
      - name: tinyproxy
        image: dannydirect/tinyproxy
        ports:
        - containerPort: 8888
        volumeMounts:
        - name: tinyproxy-config
          mountPath: /etc/tinyproxy
      volumes:
        - name: tinyproxy-config
          configMap:
            name: tinyproxy-config
