# harness.io/skip-file-for-deploy
apiVersion: v1
kind: Service
metadata:
  name: tinyproxy-service
spec:
  selector:
    app: tinyproxy
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888
  type: ClusterIP
