apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.name}}-deployment
  labels:
    app: {{.Values.name}}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: {{.Values.name}}
  template:
    metadata:
      labels:
        app: {{.Values.name}}
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: 8080
        prometheus.io/scrape: true
    spec:
      containers:
      - name: {{.Values.name}}
        image: {{.Values.image}}:{{.Values.tag}}
        ports:
        - containerPort: 8080
        env:
          {{- range $key, $value := .Values.env.config }}
          - name: {{ $key }}
            value: {{ $value | quote }}
          {{- end }}
