apiVersion: apps/v1
kind: Deployment
metadata:
  name: pcf-go-sample-app-deployment
  labels:
    app: pcf-go-sample-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pcf-go-sample-app
  template:
    metadata:
      labels:
        app: pcf-go-sample-app
    spec:
      containers:
      - name: pcf-go-sample-app
        image: lorenharness/pcf-go-sample-app:1.0.13
        ports:
        - containerPort: 8080
