apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.name}}-deployment
  labels:
    app.kubernetes.io/name: {{.Values.name}}-deployment
    app: {{.Values.name}}
spec:
  replicas: {{.Values.replicas}}
  selector:
    matchLabels:
      app: {{.Values.name}}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{.Values.name}}-deployment
        app: {{.Values.name}}
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: 8080
        prometheus.io/scrape: true
    spec:
      containers:
      - name: {{.Values.name}}
        image: {{.Values.image}}:{{.Values.tag}}
        ports:
        - containerPort: 8080
        env:
          - name: KUBERNETES_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: KUBERNETES_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: KUBERNETES_CONTAINER_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: DEPLOYMENT_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.labels['app.kubernetes.io/name']             
          {{- range $key, $value := .Values.env.config }}
          - name: {{ $key }}
            value: {{ $value | quote }}
          {{- end }}
